### ISSUE TITLE
dividir o mapa

### ISSUE THREAD

**Issue by lucascunha1979** [mryanjulian/Coronavirus_Spread#1]
hello Julian, how are you?

really perfect your code

could you tell me how you could split the map into countries and their specific states?

**Comment by mryanjulian** [comment]
Hi Lucas,

Thanks!  I’m glad you like it.

Fortunately, the .csv files that my program loads from the Johns Hopkins University CSSE GitHub already have latitude and longitude data for each location that has reported coronavirus cases.  I just use those coordinates as the center point for each circle I plot onto the map.  There’s a slight shift/merge in the positions of some circles around 3/10 and 3/11 because the group maintaining the database changed the reporting on those dates to track cases in the US and China only by state/province level instead of county or city level.  I might write a fix for that next week if I have time; it would probably require parsing the table for any row with county data and merging it with the row for the state level data.  This could also be done to merge the data at the country level, but I think that would be less informative for larger countries like the US and China.

As for the map itself, I just produce that using the mpl_toolkits Basemaps package with the following lines of code:

from mpl_toolkits.basemap import Basemap
fig, ax = plt.subplots(figsize=(10,5))
earth = Basemap(ax=ax)
earth.drawcoastlines(color='#555555', linewidth=1)

Best,

Ryan



On Mar 12, 2020, at 3:40 PM, lucascunha1979 <notifications@github.com<mailto:notifications@github.com>> wrote:


hello Julian, how are you?

really perfect your code

could you tell me how you could split the map into countries and their specific states?

**Comment by lucascunha1979** [comment]
hello Ryan .. yes, I looked at Basemaps lat and long coordinates and they limit more detailed spatial analysis for individual countries ... but I will continue to research the possibilities of disaggregation and spatial correspondence of data and maps

don't stop writing..your code is very elegant

thanks for your attention and Nirvana is the best band of the 90s :)

Sincerely

Lucas

**Comment by mryanjulian** [comment]
Yeah.  I haven't looked much at what other packages are out there for map data.  There might be better ones if you're looking to partition individual countries.

Thanks for checking out my code!

-Ryan
